In [5]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense,Input

In [6]:
X = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5],
    [4,5,6]
])

y = np.array([4,5,6,7])

In [7]:
X = X.reshape((X.shape[0], X.shape[1], 1))
print(X)

[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]


In [8]:
model = Sequential()

In [9]:
model.add(Input(shape=(3,1)))

In [10]:
model.add(GRU(50, activation='tanh'))

In [11]:
model.add(Dense(1))

In [12]:
model.compile(optimizer='adam', loss='mse')

In [13]:
model.fit(X, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 668ms/step - loss: 38.0761
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 36.9856
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 35.9133
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 34.8587
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 33.8213
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 32.8005
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 31.7958
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30.8067
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 29.8326
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 28.8732
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 27.9279
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.9964
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.0783
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25.1732
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24.2808
Epo

In [14]:
test = np.array([[5,6,7]])
test = test.reshape((1,3,1))
prediction = model.predict(test)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
[[7.2048984]]
